### ISSUE TITLE
 Client token is null or empty!

### ISSUE THREAD

**Issue by Neo110** [wxiaoqi/Spring-Cloud-Admin#24]
Client token is null or empty! 这个问题具体怎么解决呀 ？能说的详细点不 ？

**Comment by hyunwoo222** [comment]
me too ~

**Comment by dreamtan** [comment]
看到码云上有人说解决了该问题，但是我按照该方法还是没解决。你们可试试
====================================================
https://gitee.com/minull/ace-security/issues/IKLEV
hpan 23天前
在 /ace-security/ace-modules/ace-admin/src/main/java/com/github/wxiaoqi/security/admin/rpc/UserRest.java 这个文件的 getAllPermission 方法上加注解：@IgnoreUserToken

这问题坑了我两天 :sob:
